calculos/calculos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('contar/', include('contar.urls'), name='contar'),
    path('timers/', include('timers.urls'), name='timers'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

calculos/contar/urls.py
from django.urls import path
from . import views

app_name = 'contar'
urlpatterns = [
    path('', views.index, name='index'),
    path('game', views.game, name='game'),
    path('game_summary_data', views.game_summary_data, name='game_summary_data'),
    # path('game_summary/<int:pn>/<str:msg>', views.game_summary, kwargs=dict(), name='game_summary'),
    path('game_summary', views.game_summary, name='game_summary'),
]

calculos/home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.HomeView.as_view()),
]

calculos/contar/models.py
import random

from django.db import models
from django.contrib.auth.models import User


class Problem(models.Model):
    pass


class AlgebraicOperation(models.Model):
    PLUS = 'PL'
    MINUS = 'MN'
    TIMES = 'ML'
    DIVIDE = 'DV'

    OPERATIONS = [
        (PLUS, 'dodawanie'),
        (MINUS, 'odejmowanie'),
        (TIMES, 'mnożenie'),
        (DIVIDE, 'dzielenie')
    ]

    result_functions = {
        PLUS: int.__add__,
        MINUS: int.__sub__,
        TIMES: int.__mul__,
    }

    operation_strings = {
        PLUS: '+',
        MINUS: '-',
        TIMES: '\\cdot',
        DIVIDE: ':'
    }

    operation = models.CharField(
        max_length=2,
        choices=OPERATIONS,
        default=TIMES,
    )

    digits = models.IntegerField(default=1)
    negative_input = models.BooleanField(default=False)

    @staticmethod
    def create(digits, operation):
        algebraic_operation, created = AlgebraicOperation.objects.get_or_create(
            digits=digits,
            operation=operation
        )
        return algebraic_operation

    def get_number(self):
        digits = int(str(self.digits))
        number = random.randint(0, 10 ** digits - 1)
        if number < 10 ** (digits - 1):
            number = random.randint(0, 10 ** digits - 1)
        if self.negative_input:
            number *= random.choice([-1, 1])
        return number

    def get_latex_string(self, number_1: int, number_2: int):
        n1_str = str(number_1) if number_1 >= 0 else f'({number_1})'
        n2_str = str(number_2) if number_2 >= 0 else f'({number_2})'
        return f'{n1_str} {self.operation_strings.get(self.operation)} {n2_str}'

    def get_new(self):
        number_1 = self.get_number()
        number_2 = self.get_number()
        algebraic_problem, created = AlgebraicProblem.objects.get_or_create(
            number_1=number_1,
            number_2=number_2,
            operation=self.operation
        )
        if created:
            algebraic_problem.result = self.result_functions.get(self.operation)(number_1, number_2)
            algebraic_problem.latex_string = self.get_latex_string(number_1, number_2)
            algebraic_problem.save()
        return algebraic_problem


class AlgebraicProblem(Problem):
    number_1 = models.IntegerField()
    number_2 = models.IntegerField()
    operation = models.CharField(max_length=2)
    result = models.FloatField(blank=True, null=True)
    latex_string = models.CharField(max_length=127, blank=True, null=True)


class ProblemSequence(models.Model):
    total = models.IntegerField()
    problems = models.ManyToManyField(Problem, through='ProblemAssignmentToSequence')


class ProblemAssignmentToSequence(models.Model):
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    problem_sequence = models.ForeignKey(ProblemSequence, on_delete=models.CASCADE)


class UserSpace(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    points = models.IntegerField(default=0)
    days_streak = models.IntegerField(default=0)
    questions_streak = models.IntegerField(default=0)
    date_of_birth = models.DateField(null=True)
    questions_solved = models.IntegerField(default=0)

calculos/contar/views.py
import json

from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse

from .models import AlgebraicOperation


def index(request):
    return render(request, 'contar/index.html')


def game(request):
    problems_no = 20
    digits_no = 1
    operation = AlgebraicOperation.create(digits_no, AlgebraicOperation.TIMES)
    problems = set()
    while len(problems) < problems_no:
        problem = operation.get_new()
        problems.add(problem)
    problems = list(problems)
    context = {
        'problems': problems,
        'results': {idx: problems[idx].result for idx in range(len(problems))}
    }

    return render(request, 'contar/game.html', context)


def game_summary_data(request):
    # problems_number = int(request.GET.get('problems_number', None))
    # attempts = request.GET.get('attempts', None)
    data = json.loads(request.body)
    problems_number = data.get('problems_number')
    attempts = data.get('attempts')
    moves_made = len(attempts) + problems_number
    ratio = moves_made / problems_number
    print('ratio:', ratio)

    if ratio == 1:
        message = 'Brawo! Bezbłędnie!'
    elif ratio < 1.1:
        message = 'Bardzo dobrze!'
    elif ratio < 1.25:
        message = 'Nieźle!'
    elif ratio < 1.5:
        message = 'Praktyka czyni mistrza!'
    else:
        message = 'Warto jeszcze poćwiczyć!'

    context = {
        'problems_number': problems_number,
        'attempts': moves_made,
        'message': message,
    }
    return JsonResponse(context)


def game_summary(request, **kwargs):
    # print('request:', request.__dict__.keys())
    # print('kwargs:', kwargs)
    context = {
        'problems_number': kwargs.get('pn'),
        'message': kwargs.get('msg')
    }

    # return render(request, 'contar/game_summary.html', context)
    return HttpResponseRedirect('/contar/game_summary.html', context)

calculos/contar/templates/contar/base.html
<!DOCTYPE html>
{% load static %}
{% load mathjax %}
<html lang="pl" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- bootstrap css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <!-- bootswatch sketchy theme css -->
    <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/sketchy/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static './contar_style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <!-- bootstrap js -->
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <!-- font awsome -->
    <script src="https://kit.fontawesome.com/696427376b.js" crossorigin="anonymous"></script>
<!--    <script defer src="{% static './textFit.min.js' %}"></script>-->
    <script defer src="{% static './contar_script.js' %}"></script>
    {% block scripts %}{% endblock %}
    <title>{% block title %}MateGoda - JagoMatyka{% endblock %}</title>
    {% mathjax_scripts %}
</head>

<body>
    <div class="container" style="min-width: 50%">
        <div id="navbar">
            {% include './navbar.html' %}
        </div>
        <div id="sidebar">
            {% block sidebar %}
            {% endblock %}
        </div>

        <div id="content">
            {% block content %}{% endblock %}
        </div>
        <!-- modal for small screens in landscape mode -->
        <div class="modal" id="small_screen_info_modal">
            <div class="modal-dialog modal-fullscreen" role="document">
                <div class="modal-content bg-warning text-dark">
                    <div class="modal-header">
                        <h5 class="modal-title">Obróć telefon</h5>
                    </div>
                    <div class="modal-body">
                        <p>Przy poziomym ułożeniu telefonu klawiatura zasłoniłaby większość ekranu.</p>
                    </div>
                    <div class="modal-footer">
                        <p>Obróć telefon, by przejść do gry.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

calculos/contar/templates/contar/game.html
{% extends "./base.html" %}
{% block title %}gramy!{% endblock %}
{% load static %}
{% load filters %}
{% block scripts %}
{% csrf_token %}
<script defer src="{% static './contar_game_script.js' %}"></script>
{% endblock %}
{% block content %}
<div class="progress">
    <div class="progress-bar progress-bar-striped progress-bar-animated bg-warning"
         role="progressbar" id="exercise_progress_bar"
         aria-valuenow="0" aria-valuemin="0" aria-valuemax="20" style="width: 0%;"></div>
</div>
<div class="alert alert-light" id="game_field">
    <div id="problem_container" class="carousel slide row align-items-center">
        <div class="carousel-inner">
            {% for problem in problems %}
            {% if forloop.counter0 %}
            <div class="carousel-item" id="problem_{{ forloop.counter0 }}">
                <div class="problem">
                    $$ {{ problem.latex_string }} $$
                </div>
            </div>
            {% else %}
            <div class="carousel-item active" id="problem_{{ forloop.counter0 }}">
                <div class="problem">
                    $$ {{ problem.latex_string }} $$
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
<div class="container">
    <div class="row align-items-center d-none d-sm-block">
        <input type="number" inputmode="numeric" id="answer" name="answer" placeholder="wpisz" class="bg-dark">
    </div>
    <div class="row justify-content-center align-items-center d-flex d-sm-none" style="width: 95%; margin: 1em auto;">
        <div id="answer_small" class="bg-dark fs-1" style="text-align: center; height: 3rem;"> </div>
    </div>
    <div class="row justify-content-center align-items-center d-flex d-sm-none" style="width: 95%; margin: 1em auto;">
        <div class="btn bg-warning text-dark fs-2 col-2" id="button_0">0</div>
        <div class="btn bg-warning text-dark fs-2 col-2" id="button_1">1</div>
        <div class="btn bg-warning text-dark fs-2 col-2" id="button_2">2</div>
        <div class="btn bg-warning text-dark fs-2 col-2" id="button_3">3</div>
        <div class="btn bg-warning text-dark fs-2 col-2" id="button_4">4</div>
        <div class="btn bg-warning text-dark fs-2 col-2" id="button_del"><i class="fa-solid fa-delete-left"></i></div>
    </div>
    <div class="row justify-content-center align-items-center d-flex d-sm-none" style="width: 95%; margin: 1em auto;">
        <div class="btn bg-warning text-dark fs-2 col-2" id="button_5">5</div>
        <div class="btn bg-warning text-dark fs-2 col-2" id="button_6">6</div>
        <div class="btn bg-warning text-dark fs-2 col-2" id="button_7">7</div>
        <div class="btn bg-warning text-dark fs-2 col-2" id="button_8">8</div>
        <div class="btn bg-warning text-dark fs-2 col-2" id="button_9">9</div>
        <div class="btn bg-warning text-dark fs-2 col-2" id="button_cls"><i class="fa-solid fa-times"></i></div>
    </div>
</div>
<div class="buttons_row row justify-content-between align-items-center gx-10 mx-auto">
    <button class="btn btn-lg btn-info carousel-prev col-auto mx-auto" id="prev_problem" type="button">
        <i class="fa-solid fa-circle-left fa-3x"></i>
    </button>

    <button class="btn btn-lg btn-success col-auto mx-auto" id="confirm_answer" type="button">
        <i class="fa-solid fa-circle-check fa-3x"></i>
    </button>

    <button class="btn btn-lg btn-info carousel-next col-auto mx-auto" id="next_problem" type="button">
        <i class="fa-solid fa-circle-right fa-3x"></i>
    </button>
</div>

<!-- correct answer modal -->
<div class="modal" id="correct_answer_modal">
    <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
        <div class="modal-content bg-success border-0">
            <div class="modal-body bg-success fs-1 justify-content-center align-items-center" style="height: 100%">
                To jest poprawna odpowiedź!
            </div>
            <div class="modal-footer row border-success mx-0">
                <button class="btn col bg-info fs-1 border-warning" data-bs-dismiss="modal">Przejdź dalej.</button>
            </div>
        </div>
    </div>
</div>

<!-- end of ame modal -->
<div class="modal" id="end_of_game_modal">
  <div class="modal-dialog modal-fullscreen" role="document">
    <div class="modal-content bg-success">
      <div class="modal-header">
        <h5 class="modal-title">koniec gry</h5>
      </div>
      <div class="modal-body">
          <p class="fs-2">Mnożeń: <span id="problems_number"></span>.</p>
          <p class="fs-3">Twoich prób: <span id="attempts"></span>.</p>
          <div class="fs-2"><span id="message"></span></div>
      </div>
      <a href="{% url 'contar:index' %}" class="btn btn-lg btn-warning text-danger">
          zakończ
      </a>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

<!-- results in json for js -->
<script id="problems_data" type="application/json">
    {{ results|to_json }}
</script>
{% endblock %}

calculos/contar/templates/contar/game_summary.html
{% extends "./base.html" %}
{% block title %}gramy!{% endblock %}
{% load static %}
{% load filters %}
{% block content %}
<p></p>
<div class="container">
    <div class="row">
        <div class="card text-white bg-success mb-3" style="max-width: 20rem;">
            <div class="card-header">koniec gry</div>
            <div class="card-body">
                <h4 class="card-title">{{ problems_number }} mnożeń</h4>
                <p class="card-text">{{ message|linebreaks }}</p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

calculos/contar/templates/contar/index.html
{% extends "./base.html" %}
{% block title %}gramy!{% endblock %}
{% load static %}
{% load filters %}
{% block content %}
<p></p>
<div class="container">
    <div class="row">
        <a href="{% url 'contar:game' %}" class="btn btn-lg btn-warning text-danger">
            <i class="fa-solid fa-fire-flame-curved"></i>
            ZAGRAJ
        </a>
    </div>
    <p></p>
    <ul class="list-group">
        <li class="list-group-item list-group-item-info d-flex justify-content-between align-items-center">
            <i class="fa-regular fa-hourglass-half"></i>
            Twoje dni
            <span class="badge bg-info text-primary rounded-pill">??</span>
        </li>
        <li class="list-group-item list-group-item-warning d-flex justify-content-between align-items-center">
            <i class="fa-regular fa-star"></i>
            Twoje gwizadki
            <span class="badge bg-warning text-primary rounded-pill">??</span>
        </li>
        <li class="list-group-item list-group-item-danger d-flex justify-content-between align-items-center">
            <i class="fa-solid fa-certificate"></i>
            Twoje odznaki
            <span class="badge bg-danger text-primary rounded-pill">??</span>
        </li>
        <li class="list-group-item list-group-item-success d-flex justify-content-between align-items-center">
            <i class="fa-solid fa-fire-flame-curved"></i>
            Twoje gry
            <span class="badge bg-success text-primary rounded-pill">??</span>
        </li>
    </ul>
</div>

{% endblock %}

calculos/contar/templates/contar/navbar.html
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'contar:index' %}">
      <span class="badge rounded-pill bg-success">
        <i class="fa-solid fa-house"></i>
        <i class="fa-solid fa-calculator"></i>
      </span>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor03">
      <ul class="navbar-nav me-auto">
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="#">-->
<!--            <span class="badge rounded-pill bg-danger text-warning">-->
<!--              <i class="fa-regular fa-star"></i>-->
<!--              12 / 14-->
<!--            </span>-->
<!--          </a>-->
<!--        </li>-->
        <li class="nav-item">
          <a class="nav-link" href="#">
            <span class="badge rounded-pill bg-info">Info</span>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav me-end">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            <span class="badge rounded-pill bg-warning text-secondary">
              <i class="fa-regular fa-user"></i>
            </span>
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Separated link</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">
            <span class="badge rounded-pill bg-dark">
              <i class="fa-solid fa-circle-half-stroke"></i>
            </span>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>