calculos/calculos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('contar/', include('contar.urls'), name='contar'),
    path('timers/', include('timers.urls'), name='timers'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

calculos/home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.HomeView.as_view()),
]

calculos/timers/urls.py
from django.urls import path
from . import views

app_name = 'timers'
urlpatterns = [
    path('', views.collection_list, name='collection_list'),
    path('done', views.collection_done, name='collection_done'),
    path('summary', views.collection_summary, name='collection_summary'),
    path('<int:pk>/edit', views.collection_edit, name='collection_edit'),
    path('<int:pk>/run', views.collection_run, name='collection_run'),
]

calculos/timers/models.py
from django.db import models


class Collection(models.Model):
    name = models.CharField(max_length=32)

    def total_time(self):
        total = 0
        for task in self.task_set.all():
            total += task.seconds
        return total

    def __str__(self):
        return f'{self.name} ({self.pk})'


class Task(models.Model):
    name = models.CharField(max_length=32)
    seconds = models.IntegerField()
    order = models.IntegerField()
    collection = models.ForeignKey(Collection, on_delete=models.CASCADE)

calculos/timers/views.py
import json
from django.core.exceptions import ObjectDoesNotExist
from django.http import JsonResponse
from django.shortcuts import render
from .models import Collection, Task


def collection_list(request):
    collections = Collection.objects.all()
    context = {
        'collections': [(collection, collection.total_time()) for collection in collections]
    }
    return render(request, 'timers/collection_list.html', context)


def get_collection_context(pk):
    try:
        collection = Collection.objects.get(pk=pk)
    except ObjectDoesNotExist:
        print(f'no collection with id {pk}')
        return None

    tasks = [task for task in collection.task_set.iterator()]
    tasks.sort(key=lambda x: x.order)

    context = {
        'collection': collection,
        'tasks': tasks
    }
    return context


def collection_edit(request, pk):
    if context := get_collection_context(pk):
        return render(request, 'timers/collection_edit.html', context)
    else:
        return collection_list(request)


def collection_run(request, pk):
    if context := get_collection_context(pk):
        tasks = context.get('tasks', [])
        tasks_list = [
            {
                'name': task.name,
                'total_time': task.seconds * 1000,
                'order': task.order,
                'time_spent': 0,
                'time_left': task.seconds * 1000,
                'status': 0,
                'exceeded': False,
            } for task in tasks
        ]
        context['tasks'] = tasks_list
        context['data'] = json.dumps(tasks_list)
        return render(request, 'timers/collection_run.html', context)
    else:
        return collection_list(request)


def collection_done(request):
    result = json.loads(request.body)
    tasks_updated = result.get('tasks')
    # for task in tasks_updated:
    #     print(task)
    # return render(request, 'timers/collection_done.html', context={'result': result})
    return JsonResponse({'tasks': tasks_updated})


def collection_summary(request):
    return render(request, 'timers/collection_done.html', context={'result': 1})

calculos/timers/templates/timers/base.html
<!DOCTYPE html>
{% load static %}
{% load mathjax %}
{% load time_temp %}
<html lang="pl" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- bootstrap css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <!-- bootswatch sketchy theme css -->
    <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/flatly/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static './timers_style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <!-- bootstrap js -->
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <!-- font awsome -->
    <script src="https://kit.fontawesome.com/696427376b.js" crossorigin="anonymous"></script>
<!--    <script defer src="{% static './textFit.min.js' %}"></script>-->
    <script defer src="{% static './timers_script.js' %}"></script>
    {% block scripts %}{% endblock %}
    <title>{% block title %}Minutnik{% endblock %}</title>
    {% mathjax_scripts %}
</head>

<body>
    <div class="container" style="min-width: 50%">
        <div id="navbar">
            {% include './navbar.html' %}
        </div>
        <div id="sidebar">
            {% block sidebar %}
            {% endblock %}
        </div>

        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>

calculos/timers/templates/timers/collection_edit.html
{% extends "./base.html" %}
{% block title %}3, 2, 1...!{% endblock %}
{% load static %}
{% load filters %}
{% load time_temp %}
{% csrf_token %}
{% block scripts %}
<script defer src="{% static './timers_script_edit.js' %}"></script>
{% endblock %}
{% block content %}
<div class="collection-content">
    <ul class="sortable-list">
        {% for task in tasks %}
        <li class="item" draggable="true">
            <a href="{% url 'timers:collection_edit' collection.id %}">
                <div class="details">{{ task.name }}</div>
            </a>
            <a href="{% url 'timers:collection_edit' collection.id %}">
                <div class="details">{{ task.seconds|time_view_seconds }}</div>
            </a>
            <a href="{% url 'timers:collection_edit' collection.id %}">
                <i class="fa-regular fa-pen-to-square text-info"></i>
            </a>
            <a href="{% url 'timers:collection_edit' collection.id %}">
                <i class="fa-solid fa-xmark text-danger"></i>
            </a>
            <a href="{% url 'timers:collection_edit' collection.id %}">
                <i class="fa-solid fa-grip-vertical"></i>
            </a>
        </li>
        {% endfor %}
        <li class="item item-add">
            <a href="{% url 'timers:collection_edit' collection.id %}">
                <div class="details"><pre>   </pre></div>
            </a>
            <a href="{% url 'timers:collection_edit' collection.id %}">
                <div class="details"><strong>dodaj</strong></div>
            </a>
            <a href="{% url 'timers:collection_edit' collection.id %}">
                <i class="fa-solid fa-plus text-success"></i>
            </a>
            <a href="{% url 'timers:collection_run' collection.id %}">
                <i class="fa-solid fa-play text-success" style="visibility: hidden;"></i>
            </a>
            <a href="{% url 'timers:collection_edit' collection.id %}">
                <i class="fa-solid fa-plus text-success" style="visibility: hidden;"></i>
            </a>
        </li>
        <li class="item item-add">
            <a href="{% url 'timers:collection_run' collection.id %}">
                <div class="details"></div>
            </a>
            <a href="{% url 'timers:collection_run' collection.id %}">
                <div class="details"><strong>start</strong></div>
            </a>
            <a href="{% url 'timers:collection_run' collection.id %}">
                <i class="fa-solid fa-play text-success"></i>
            </a>
            <a href="{% url 'timers:collection_run' collection.id %}">
                <i class="fa-solid fa-play text-success" style="visibility: hidden;"></i>
            </a>
            <a href="{% url 'timers:collection_run' collection.id %}">
                <i class="fa-solid fa-play text-success" style="visibility: hidden;"></i>
            </a>
        </li>
    </ul>
</div>
{% endblock %}

calculos/timers/templates/timers/collection_list.html
{% extends "./base.html" %}
{% block title %}3, 2, 1...!{% endblock %}
{% load static %}
{% load filters %}
{% load time_temp %}
{% csrf_token %}
{% block scripts %}
<script defer src="{% static './timers_script.js' %}"></script>
{% endblock %}
{% block content %}

{% if collections %}
<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">lp</th>
            <th scope="col">tytuł</th>
            <th scope="col">czas</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for collection, total_time in collections %}
        <tr>
            <th scope="row">
                {{ forloop.counter }}
            </th>
            <td>
                <a href="{% url 'timers:collection_edit' collection.id %}">
                    <i class="fa-solid fa-play text-success"></i>
                    <span> {{ collection.name }}</span>
                </a>
            </td>
            <td>
                {{ total_time|time_view_seconds }}
            </td>
            <td>
                <a href="#"><i class="fa-solid fa-pen text-info"></i></a>
                <a href="#"><i class="fa-solid fa-xmark text-danger"></i></a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}
{% endblock %}

calculos/timers/templates/timers/collection_run.html
{% extends "./base.html" %}
{% block title %}3, 2, 1...!{% endblock %}
{% load static %}
{% load filters %}
{% load time_temp %}
{% csrf_token %}
{% block scripts %}
<script>
    let tasks = JSON.parse("{{data|escapejs}}");
    let collection_id = {{collection.id|escapejs}};
</script>
<script defer src="{% static './timers_script_run.js' %}"></script>
{% endblock %}
{% block content %}

<div class="container border-bottom border-top border-warning" id="total-time">
    <div class="row">
        <div class="col text-center text-info display-2" id="total-time-spent">
        </div>
        <div class="col text-center text-success display-2" id="total-time-left">
        </div>
    </div>
</div>
{% for task in tasks %}
<div class="container hidden border-bottom border-warning" id="container-{{ task.order }}">
    <div class="row">
        <div class="col text-center task-name display-1 text-uppercase text-warning">
            {{ task.name }}
        </div>
    </div>
    <div class="row">
        <div class="col text-center text-info display-2" id="task-time-spent-{{ task.order }}">
            {{ task.time_spent|time_view }}
        </div>
        <div class="col text-center text-success display-2" id="task-time-left-{{ task.order }}">
            {{ task.time_left|time_view }}
        </div>
    </div>
</div>
{% endfor %}
<div class="container" id="buttons">
    <div class="row"></div>
    <div class="row justify-content-center">
        <div class="col-3 text-center display-1" id="backward">
            <i class="fa-solid fa-backward-step text-info run_icon"></i>
        </div>
        <div class="col-3 text-center display-1" id="accept">
            <i class="fa-regular fa-circle-check text-success run_icon"></i>
        </div>
        <div class="col-3 text-center display-1" id="forward">
            <i class="fa-solid fa-forward-step text-info run_icon"></i>
        </div>
    </div>
    <div class="row"></div>
    <div class="row"></div>
    <div class="row justify-content-end">
        <a href="{% url 'timers:collection_list' %}" class="col-2 display-2 text-primary" id="finish">
            <i class="fa-solid fa-flag-checkered run_icon"></i>
        </a>
    </div>
</div>

<div class="container hidden" id="summary">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col" rowspan="2">lp</th>
                <th scope="col" rowspan="2">nazwa</th>
                <th colspan="3">czas</th>
            </tr>
            <tr>
                <th scope="col">cały</th>
                <th scope="col">użyty</th>
                <th scope="col">zostało</th>
            </tr>
        </thead>
        <tbody>
            {% for task in tasks %}
            <tr>
                <th scope="row" id="lp-{{ task.order }}"></th>
                <td>{{ task.name }}</td>
                <td>{{ task.total_time|time_view }}</td>
                <td id="summary-spent-{{ task.order }}">{{ task.time_spent|time_view }}</td>
                <td id="summary-left-{{ task.order }}">{{ task.time_left|time_view }}</td>
            </tr>
            {% endfor %}
            <tr>
                <th></th>
                <th>razem</th>
                <th id="summary-total-time"></th>
                <th id="summary-total-spent"></th>
                <th id="summary-total-left"></th>
            </tr>
        </tbody>
    </table>
</div>

{% endblock %}

calculos/timers/templates/timers/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'timers:collection_list' %}">
      <i class="fa-solid fa-house"></i>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarColor03">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link" href="#">
            Info
          </a>
        </li>
      </ul>
      <ul class="navbar-nav me-end">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            <i class="fa-regular fa-user"></i>
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Separated link</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">
            <i class="fa-solid fa-circle-half-stroke"></i>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>